### ISSUE TITLE
JSON-RPC request stays pending

### ISSUE THREAD

**Issue by shanejonas** [etclabscore/jade-service-runner#106]
**Describe the bug**
JSON-RPC requests stays pending, then timeout.

**To Reproduce**
1. Start Service Runner
1. Go to Postman
1. create request
1. See error

**Expected behavior**
Expect response from service runner

**Screenshots**
![image](https://user-images.githubusercontent.com/364566/62414262-c33d2c00-b5cd-11e9-8ab5-f96084cee7ea.png)
![image](https://user-images.githubusercontent.com/364566/62414263-cdf7c100-b5cd-11e9-90ef-d491aada7441.png)

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser: Postman

**Comment by zcstarr** [comment]
Great find! This was a terrible issue :D . In an effort to keep request in equivalent to the request out, I was simply forwarding all data. However, because service runner needs to introspect some of that data. It means transforming the original request, and verifying its JSON-RPCness. Because of that some bits like \r\\r\0\n etc... were being trimmed from the original request. 

A header length of 84 in the example case above becomes 116 when the request is made from postman or curl. So when the request came in, the JSON body parser was expecting the data stream to contain more data, but would "hang" the process because more data would not come. Timing out the request.

The solution was to simply recode the data coming over the wire with a new headers.
